services:
  kartverketweb:
    image: kartverketweb
    build:
      context: .
      dockerfile: Kartverket.Web/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=mariadbcontainer;port=3306;database=mysql;user=root;password=Erfan1234
    networks:
      - appnet

networks:
  appnet:
    external: true
    name: appnet
